#!/usr/bin/env sh

sudo pacman -S --noconfirm \
	pulseaudio \
	pulseaudio-alsa \
	pulseaudio-bluetooth \
	pulseaudio-equalizer \
	pulseaudio-jack \
	apulse \
	pamixer \
	pavcontrol \
	brightnessctl \
	bluez \
	bluez-utils \
	blueman \
	network-manager-applet

systemctl enable --now bluetooth
