#!/usr/bin/env sh

_SESSIONS=(~/STORAGE/KITTY_SESSIONS/*)

for i in "${_SESSIONS[@]}"; do
	name=${i##*/}
	# Except test configurations which start with prefix "_"
	if [[ ! $name =~ ^_ ]]; then
		echo $name
	fi
done
